{% set name = "patchelf" %}
{% set version = "0.19.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/NixOS/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: 2cce01de93653829f6ab68a20c2ec275e1c00a946110704a27e928d2e6e88716
  patches:
    - patches/0001-disable-rpath-tests-on-linux.patch  # [linux]

build:
  number: 0
  binary_relocation: False
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - automake
    - autoconf
    - libtool
    - m4
    # needed for tests
    - binutils  # [linux]

test:
  commands:
    - bash -c '[[ "$(patchelf --version)" =~ "patchelf {{ version }}".* ]]'  # [unix]

about:
  home: https://github.com/NixOS/patchelf
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: A small utility to modify the dynamic linker and RPATH of ELF executables.
  description: |
    PatchELF is a small utility to modify the dynamic linker and RPATH of ELF
    executables.
  doc_url: https://github.com/NixOS/patchelf/blob/master/README.md
  dev_url: https://github.com/NixOS/patchelf

extra:
  recipe-maintainers:
    - jakirkham
    - mjuric
