{% set version = "0.12" %}

package:
  name: patchelf
  version: {{ version }}

source:
  url: https://github.com/NixOS/patchelf/archive/{{ version }}.tar.gz
  sha256: 3dca33fb862213b3541350e1da262249959595903f559eae0fbc68966e9c3f56
  patches:
    # Fix unsupported overlap of SHT_NOTE and PT_NOTE
    # See https://github.com/NixOS/patchelf/pull/230
    - 6edec83653ce1b5fc201ff6db93b966394766814.patch
    - 0001-build-id.patch
    - 0002-remove-broken-test-r-path.patch

build:
  number: 1
  script: build.sh  # [win]
  binary_relocation: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m2w64-toolchain  # [win]
    - patch  # [unix]
    - m2-patch  # [win]
    - make  # [unix]
    - m2-make  # [win]
    - automake
    - autoconf

test:
  commands:
    - bash -c '[[ "$(patchelf --version)" =~ "patchelf {{ version }}".* ]]'  # [unix]
    - patchelf --version  # [win]

about:
  home: http://nixos.org/patchelf.html
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: A small utility to modify the dynamic linker and RPATH of ELF executables.
  description: |
    PatchELF is a small utility to modify the dynamic linker and RPATH of ELF
    executables.
  doc_url: http://nixos.org/patchelf.html
  dev_url: https://github.com/NixOS/patchelf

extra:
  recipe-maintainers:
    - jakirkham
    - mjuric
