{% set name = "patchelf" %}
{% set version = "0.19.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/NixOS/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: b189d3ec57730757895b9e7d3a1f136d3af96ec9228ae6ef0a07c20a213f28f5

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch  # [unix]
    - make  # [unix]
    - automake
    - autoconf
    - libtool
    - m4
    # needed for tests
    - binutils  # [linux]

test:
  commands:
    - bash -c '[[ "$(patchelf --version)" =~ "patchelf {{ version }}".* ]]'  # [unix]

about:
  home: https://github.com/NixOS/patchelf
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: A small utility to modify the dynamic linker and RPATH of ELF executables.
  description: |
    PatchELF is a small utility to modify the dynamic linker and RPATH of ELF
    executables.
  doc_url: https://github.com/NixOS/patchelf/blob/master/README.md
  dev_url: https://github.com/NixOS/patchelf

extra:
  recipe-maintainers:
    - jakirkham
    - mjuric
