travis:
  secure:
    BINSTAR_TOKEN: d82OZsNe3vyqkNqiNHvUPiIbwmuvZ5zZII3Kbz3WP0wuL6twJoXlHSznwUHIaTgVklLCDFXrDf4G1BrlbcOIgFjhm/fQ8z5XQZMgugSRf7/Hn2FAaZnvu+mnt9tSd2IHBvT8uPfVfcaaA3TQC9tzj1VNm8N3Jh25VlqStwVQszqdN67tRSkZdJR1RsRyJ8BFiHOwGrszIFU9V47GEoIM58zqySE7h8CJ46eNf0Ovsm+FLPlA4d+uNSnbfE2C63Vb8wQ5MSwOwOSU+kha/btVH+agQRmDG/58ZgFqwx2OoLyql0Ez7/MQ7XryhfJEaLt12uU+Zoa9wSjkLBFzZMNMDR0ard1GvI7P8X2/6fI8eIEcOjdWcMvb+/N4ol/vMDSRTcNxxUbR5qoHLVs//VwsQFStl4WxlBQjab3bXH83Gqagt6A8l933cKzK8+DSV5qKbxZq+6c1+XHF3v1G2CuPqAjhiNiSoaPTnZ1GQiao9RiSKev37EihR4YThHRlzU9kNkZPdInHesDgyLj4Eg5aRyOzQ0kPZzx33HbPwOuDdI0+H+7rBFIuhEyRk55HNBPtYcU/ZOA9yxWKrgcJhA3w6uoyxSggH6XFTW9YkyhPjPjzv9qOlxCIzy0QDKJZ7tYc89T9sic6eY9xQjlA2FCamD9C9iI1WQJZWaZ2YCWQm34=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
