appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: m37yTczLNXA6IEhS3EkD/L0Qukvanpjd/GjGzDHRsCRpwesXg846Vis6rndbRKy3XemvmOzNvbofhcYpcXn0XU5MsLuEHYF/a5OlvnH2l1F4IhN3eiFJAEd98hqUt/cHi5d4aIoRYBX1fTSGyCOGqrlfWELqZOiaxHn+Rr69n0Hzz5TdgugJ4zwZgIsfr1KVyHfI/4Djv9lYtwfGk/h9UW1SQayMweRRC4SgOwfoT70ATVUqeTlye/MVnmQf29bIxxBjm94i108myHD+NAGG7/K8aFAm3pvcggo/J37Wo2vyrw5ApmdoFvRSOP/gFk5keUosGJ8nVt02CpMIuNDpUvyt9ggKJi9t63zMwzXOPK4GFzo3WUWNOfY/rdCJMwPMyHqFfZnBQSr4/b/eHvakMsFfs9fcK3smAsyrpCjDi8+YB0aDuMCUy+djmZravgsI1B+zq8xef7I7pWgQF0v7XhnhVmhshoIpecwKTTPao+izPAExw/52bOmqzphpSrbEEBRVq3y/qqA17UkOBKa4Ut7ykantJ6pLVPTIxXHdsuerhv8hkGhRlAlgKzsUtyKayqtrI3rlNWkfyJ0xvS+s/B7KKQhpG1Zkem8h7l+z5LZgcdjmSckNSXIjcf5wbSgcR4PHwR5m4tblLDoxbTvmEH8Fd+MLZLYg+chPrzqczJw=}
